name: Build and deploy

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
  schedule:
    - cron: '22 23 * * 2'
  workflow_dispatch:

jobs:
  build-java:
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        version: [ '17', '21', '22' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: java
          platforms: linux/amd64,linux/arm64
          build-args: base_image=eclipse-temurin:${{matrix.version}}-jre
          pull: true
          push: ${{ github.ref_name == 'master' }}
          tags: ghcr.io/${{ github.repository }}/java:${{matrix.version}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
  trivy:
    needs: [build-java]
    permissions:
      actions: read
      contents: read
      security-events: write
    name: Trivy
    uses: navikt/fp-gha-workflows/.github/workflows/trivy.yml@main
    with:
      build-version: 'java:21'
    secrets: inherit
