name: Build and deploy

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
  schedule:
    - cron: '23 23 * * 2'
  workflow_dispatch:

jobs:
  build-java:
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        version: [ '17', '21', '23' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push GAR
        uses: nais/docker-build-push@v0
        with:
          docker_context: java
          platforms: linux/amd64,linux/arm64
          build_args: |
            base_image=eclipse-temurin:${{matrix.version}}-jre
          pull: true
          push_image: ${{ github.ref_name == 'master' }}
          tag: latest
          cache_from: type=gha
          cache_to: type=gha,mode=max
          team: teamforeldrepenger
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

  trivy:
    needs: [build-java]
    permissions:
      actions: read
      contents: read
      security-events: write
    name: Trivy
    uses: navikt/fp-gha-workflows/.github/workflows/trivy.yml@main
    with:
      build-version: 'java:23'
    secrets: inherit
