name: Build and deploy

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
  schedule:
    - cron: '22 23 * * 2'
  workflow_dispatch:

jobs:
  build-java:
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        version: [ '17', '19' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: java
          platforms: linux/amd64,linux/arm64
          build-args: base_image=eclipse-temurin:${{matrix.version}}-jre
          pull: true
          push: ${{ github.ref_name == 'master' }}
          tags: ghcr.io/${{ github.repository }}/java:${{matrix.version}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-java-appd:
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        version: [ '17', '19' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: java/appdynamics
          platforms: linux/amd64,linux/arm64
          build-args: base_image=eclipse-temurin:${{matrix.version}}-jre
          pull: true
          push: ${{ github.ref_name == 'master' }}
          tags: ghcr.io/${{ github.repository }}/java:${{matrix.version}}-appdynamics
          cache-from: type=gha
          cache-to: type=gha,mode=max

  trivy:
    needs: build-java-appd
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      matrix:
        image_version: [ 'java:17-appdynamics', 'java:19-appdynamics' ]
    name: Trivy
    uses: navikt/fp-gha-workflows/.github/workflows/trivy.yml@main
    with:
      build-version: ${{matrix.image_version}}
    secrets: inherit
