name: Build and deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
  schedule:
    - cron: '22 23 * * 2'
  workflow_dispatch:

env:
  IMAGE_JAVA: ghcr.io/${{ github.repository }}/java
  IMAGE_NODE: ghcr.io/${{ github.repository }}/node-express

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Build all images
        run: make -j

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # Use commit-sha1 instead of tag for security concerns
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push images
        run: |
          docker push ${IMAGE_JAVA}:17
          docker push ${IMAGE_JAVA}:17-appdynamics
          docker push ${IMAGE_JAVA}:18
          docker push ${IMAGE_JAVA}:18-appdynamics
          docker push ${IMAGE_JAVA}:19
          docker push ${IMAGE_JAVA}:19-appdynamics
          docker push ${IMAGE_NODE}:14
          docker push ${IMAGE_NODE}:16
          docker push ${IMAGE_NODE}:18
          

