name: Package cleanup
on:
  workflow_dispatch:
  schedule:
    - cron: '48 4 * * 3'

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: fp-baseimages/java
          package-type: container
          min-versions-to-keep: 10
          delete-only-untagged-versions: true
