name: Snyk vulnerabilities scanning of dependencies
on:
  schedule:
    - cron:  '30 5 * * 3'
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/snyk.yml'

jobs:
  snyk:
    strategy:
      matrix:
        image_version: [ 'java:17', 'java:19', 'java:17-appdynamics', 'java:19-appdynamics', 'node-express:16', 'node-express:18', 'node-express:19' ]
    runs-on: ubuntu-latest
    steps:
      - name: Run Snyk to check Docker images for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          image: ghcr.io/${{ github.repository }}/${{matrix.image_version}}
          args: --org=teamforeldrepenger --severity-threshold=critical --project-name=${{ github.repository }}
