name: Trivy vulnerabilities scanning of dependencies
on:
  schedule:
    - cron:  '* * * * 6'
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/trivy.yml'

jobs:
  trivy:
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      matrix:
        image_version: [ 'java:17-appdynamics', 'java:19-appdynamics' ]
    name: Trivy
    uses: navikt/fp-gha-workflows/.github/workflows/trivy.yml@main
    with:
      build-version: ${{matrix.image_version}}
    secrets: inherit
